[package]
name = "ppsaver"
version = "0.1.0"
edition = "2021"

[dependencies]
cronjob = "0.4.17"
once_cell = "1.17.1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = "1.0.130"
colored = "2"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
