[package]
name = "ppsaver"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
cronjob = "0.4.17"
once_cell = "1.17.1"
reqwest = { version = "0.11", features = ["blocking"] }
rust-embed="6.6.0"
serde = "1.0.130"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
