[package]
name = "pp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.130"
reqwest = { version = "0.11", features = ["blocking"] }

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
